import fs from "node:fs/promises";
import path from "node:path";

const BASE_HASHTAGS = ["#MilesAndMeals", "#TravelDiaries", "#FoodAndTravel", "#SlowTravel", "#TravelStory"];

const LOCATION_PLACEHOLDER = "Location: __________";

function subjectFromFilename(filename) {
  const subject = filename.replace(/\.[^.]+$/, "").replace(/[-_]+/g, " ").trim();
  return subject.length > 0 ? subject : "this moment";
}

export function buildPostingPackage({ filename, relativePath }) {
  const subject = subjectFromFilename(filename);
  const generatedAt = new Date().toISOString();

  return {
    filename,
    relativePath,
    generatedAt,
    caption: {
      draft:
        `A travel moment worth slowing down for: ${subject}.\n\n` +
        `${LOCATION_PLACEHOLDER}\n\n` +
        "Add the real story here before posting — what made this moment worth sharing.",
      notes:
        "Draft only. This caption does not assume a location, invent an experience, or state any fact about the trip. Replace the placeholder and add the authentic story before publishing."
    },
    hashtags: [...BASE_HASHTAGS],
    altText: {
      draft: `Travel photo titled "${subject}".`,
      notes:
        "Draft only, based on the filename, not the image contents. Replace with a precise description of what is actually visible in the photo before publishing."
    },
    checklist: [
      "Caption reviewed",
      "Location verified",
      "Hashtags reviewed",
      "ALT text reviewed",
      "Image quality checked",
      "Ready to publish"
    ],
    processingLog: [
      {
        timestamp: generatedAt,
        event: "posting_package.generated",
        message: "Posting package generated by Automation 2. Draft only; nothing was published."
      }
    ]
  };
}

export function renderPostingPackageMarkdown(pkg) {
  const lines = [
    `# Posting Package: ${pkg.filename}`,
    "",
    `- Image: \`${pkg.relativePath}\``,
    `- Generated: ${pkg.generatedAt}`,
    "",
    "## Suggested Caption (Draft)",
    "",
    pkg.caption.draft,
    "",
    `_${pkg.caption.notes}_`,
    "",
    "## Suggested Hashtags",
    "",
    pkg.hashtags.join(" "),
    "",
    "## ALT Text (Draft)",
    "",
    pkg.altText.draft,
    "",
    `_${pkg.altText.notes}_`,
    "",
    "## Posting Checklist",
    "",
    ...pkg.checklist.map((item) => `- [ ] ${item}`),
    "",
    "## Processing Log",
    "",
    ...pkg.processingLog.map((entry) => `- ${entry.timestamp} — ${entry.event}: ${entry.message}`),
    "",
    "---",
    "",
    "This package is a draft only. Automation 2 does not publish content, does not connect to Instagram, " +
      "and never modifies the original image. Review and complete every item above, then post manually.",
    ""
  ];

  return lines.join("\n");
}

export async function writePostingPackage(packagePath, pkg) {
  await fs.mkdir(path.dirname(packagePath), { recursive: true });
  const markdown = renderPostingPackageMarkdown(pkg);
  const tempPath = `${packagePath}.tmp-${process.pid}-${Date.now()}`;

  try {
    await fs.writeFile(tempPath, markdown, "utf8");
    await fs.rename(tempPath, packagePath);
  } catch (error) {
    await fs.unlink(tempPath).catch(() => {});
    throw error;
  }
}
